services:
  ui-tars:
    build: 
      context: ./ui-tars
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    volumes:
      - ./ui-tars-7b-dpo:/models/ui-tars-7b-dpo
    restart: unless-stopped

  pdf-generator:
    build: 
      context: ./pdf-service
      dockerfile: Dockerfile
    ports:
      - "8002:8000"
    volumes:
      - ./reports:/app/reports
    depends_on:
      - ui-tars
    restart: unless-stopped